### ISSUE TITLE
New format of file in phasmophobia beta.

### ISSUE THREAD

**Issue by Fustie** [chromamods/phasmo-save-editor#1]
Now i has 3 files in my game directory:
saveData.txt (doesn't use)
New:
SaveFile.es3
SaveFile.es3.tmp.bak

And so saveData changes don't affect on anything in your game.

**Comment by Lyraedan** [comment]
@Fustie if you delete SaveFile.es3 files, delete the steam cloud file, turn off steam cloud in properties and replace the save file it works, just simply turn steam cloud back on when playing and complete a match
